beamline: bl45p
namespace: epics-iocs
base_image: ghcr.io/epics-containers/ioc-adsimdetector:2.10r3.0.run

# root folder of generic ioc source - not expected to change
iocFolder: /epics/ioc

# useAffinity - when true: only run on nodes with label beamline:bl45p
useAffinity:
# use default resource limits
memory: 8Gi
cpu: 2

# when autosave is true: create PVC and mount at /autosave
autosave: false

# use the default account (at DLS this means your own fed ID), default false
noServiceAccount: true

# add a 50GB PVC in /data, default false
dataVolume: true

# add a Service to expose UDP and TCP 5064 for Channel Access, default false
# set this to true is you have hostNetwork=false and want Channel access
# from outside
addService: true

# set hostNetwork=true for direct access to the Network. Requires a
# privileged pod and wont be available at DLS unless you are using the
# default service account in epics-iocs called priv-epics-iocs
hostNetwork: false
